# SKILLNAV : Analyse exploratoire du marché Data & IA (Maroc + International)

> **Module** : M242 Analyse de Web · ENSA-Tétouan · Pr. Imad Sassi
> **Auteurs** : Karamo Sylla & Bachirou Konaté · **Soutenance** : 28 mai 2026

---

## Objectif

Première lecture chiffrée du corpus SKILLNAV collecté en mai 2026, **niveau
EDA descriptive** : qui recrute, quels métiers, quelles compétences, sur
quelles plateformes. Les **visualisations** correspondantes (16 figures
exportées en PNG) sont dans le notebook compagnon
[`01_visualisations.ipynb`](./01_visualisations.ipynb).

| Bloc                     | Fiches | Période              | Sources                                                                     |
|--------------------------|-------:|----------------------|-----------------------------------------------------------------------------|
| **Partie I : Maroc**     |    381 | août 2022 / mai 2026 | ANAPEC · Rekrute · Indeed MA · LinkedIn MA · Pages carrières · Glassdoor MA |
| **Partie II : INTL**     |  3 086 | août 2025 / mai 2026 | Corpus Tech INTL (builtin.com, 6 pays)                                      |
| **Partie III : Synthèse**|      . | .                    | Comparaison side-by-side et écarts marquants                                |

Toute la plomberie (chargement, canonicalisation 3 niveaux, helpers
d'analyse, fonctions de section) est dans le module `scripts/skillnav_eda.py`.
Voir [`docs/NOTEBOOK_00_ANNEXE_CODE.md`](../docs/NOTEBOOK_00_ANNEXE_CODE.md)
pour les explications pédagogiques.

## 0. Setup

In [1]:
# Import du module utilitaire SKILLNAV (chargement, canonicalisation, helpers)
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent / 'scripts'))
from skillnav_eda import *  # noqa: F401,F403

# Chargement des deux corpus + contrôle qualité automatique
df_maroc, df_international = charger_corpus()
controle_qualite(df_maroc, df_international)

Corpus chargé : 381 fiches Maroc + 3086 fiches International = 3467 total.
Contrôle qualité OK : aucun doublon dans le top 100 compétences ni top 30 titres.

### Glossaire : AI-First / AI-Support / ML-First / Data Analytics

Quatre catégories de postes utilisées tout au long du notebook, classifiées
automatiquement au moment de la collecte par Claude Sonnet 4.5 à partir du
titre, des responsabilités et des compétences requises.

| Catégorie           | Définition courte                                                     | Exemples typiques                                       |
|---------------------|-----------------------------------------------------------------------|---------------------------------------------------------|
| **AI-First**        | L'IA générative (LLM, RAG, agents) **est** le produit                 | AI Engineer, Applied AI Engineer, GenAI / LLM Engineer  |
| **AI-Support**      | Le poste appuie une équipe IA sans construire les modèles             | AI Platform Engineer, AI Solutions Engineer, MLOps Eng  |
| **ML-First**        | ML traditionnel (CV, NLP pré-LLM, RecSys, recherche)                  | ML Engineer, Research Scientist, Computer Vision Eng    |
| **Data Analytics**  | SQL, BI, ETL, Excel ; pas de modélisation prédictive forte            | Data Analyst, BI Engineer, Business Analyst             |

---

# Partie I : Marché Data & IA au Maroc (381 fiches)

## I.1 Vue d'ensemble du corpus marocain

> **Comment lire les deux derniers compteurs ?**
>
> - **Postes managériaux** : offres pour lesquelles le poste implique d'encadrer une équipe (intitulés contenant *lead, head, director, manager, VP, chief, principal*).
> - **Postes à interface client** : offres pour lesquelles le titulaire est en contact direct avec des clients externes (intitulés ou descriptions contenant *sales engineer, customer success, solutions engineer, presales*).

In [2]:
section_vue_ensemble(df_maroc, 'Maroc')

=== Vue d'ensemble (Maroc) ===
Fiches totales : 381
Sources distinctes : 6 (anapec, glassdoor-ma, indeed-ma, linkedin-ma, pages-carrieres-ma, rekrute)
Période couverte : 2022-08 -> 2026-05 (27 mois distincts)
Entreprises distinctes : 147
Postes managériaux (lead, head, director, manager) : 22 (5.8 %)
Postes à interface client (sales, customer success, solutions eng.) : 81 (21.3 %)

## I.2 Distribution par type de poste

In [3]:
section_distribution_type(df_maroc, 'Maroc')

                       Offres  % du corpus
Type de poste (Maroc)
Data Analytics            206         54.1
ML-First                  129         33.9
AI-First                   46         12.1

## I.3 Top employeurs au Maroc

In [4]:
section_top_entreprises(df_maroc, 'Maroc', top=15)

                               Offres
Top 15 employeurs (Maroc)
BROME Consulting & Technology      23
Capgemini                          20
ALTEN                              18
CIH BANK                           14
Unknown                            13
Agoda                              12
ALTEN MAROC                         9
Odixcity Consulting                 8
BNP Paribas                         7
Admiral Digital Consulting          7
SQLI                                7
SymphonyAI                          6
Devoteam                            6
Société Générale                    5
Trusted Advisors                    4

## I.4 Top intitulés de poste (canonicalisés)

Les intitulés bruts sont normalisés au chargement : `H/F`, `Hf`, `M/F`
suffixes retirés ; casse uniformisée ; alias appliqués pour les titres
fréquents (`Data Scientist` ne collisionne plus avec `Data scientist`).

In [5]:
section_top_titres(df_maroc, 'Maroc', top=10)

                                           Offres
Top 10 intitulés de poste (Maroc)
Data Analyst                                   37
Data Scientist                                 30
Data Engineer                                  23
AI Engineer                                     4
BI Analyst                                      4
Data Manager                                    4
Senior Data Engineer                            4
Data Engineer GCP (Pub/Sub, DBT)                4
Quantitative Risk Analyst / Data Analyst        3
AI Machine Learning Optimization Engineer       3

## I.5 Compétences par famille (10 catégories)

In [6]:
section_competences_par_famille(df_maroc, 'Maroc', top=8)

=== Top 8 compétences par famille (Maroc) ===

>> IA générative <<
                       Offres  % du corpus
IA générative (Maroc)
LLM                        23          6.0
GenAI                      19          5.0
Agents                     13          3.4
RAG                        11          2.9
Fine-tuning                 4          1.0
LangChain                   4          1.0
MCP                         3          0.8
Embeddings                  2          0.5

>> Machine Learning <<
                          Offres  % du corpus
Machine Learning (Maroc)
Machine Learning             147         38.6
TensorFlow                    36          9.4
PyTorch                       35          9.2
Deep Learning                 29          7.6
scikit-learn                  25          6.6
Keras                          5          1.3
XGBoost                        3          0.8
Transformers                   2          0.5

>> Web & APIs <<
                    Offres  % du corpus
Web & APIs (Maroc)
next                    39         10.2
React                    9          2.4
vue                      8          2.1
REST APIs                7          1.8
angular                  5          1.3
html5                    4          1.0
FastAPI                  4          1.0
html                     3          0.8

>> Bases de données <<
                          Offres  % du corpus
Bases de données (Maroc)
bigquery                      41         10.8
PostgreSQL                    24          6.3
Snowflake                     21          5.5
MongoDB                       10          2.6
Oracle                         6          1.6
cassandra                      6          1.6
elasticsearch                  4          1.0
Redis                          3          0.8

>> Data Engineering <<
                          Offres  % du corpus
Data Engineering (Maroc)
SQL                          218         57.2
Spark                         64         16.8
ETL                           59         15.5
hadoop                        39         10.2
Airflow                       38         10.0
Databricks                    29          7.6
Data Warehouse                28          7.3
Kafka                         27          7.1

>> Cloud <<
                    Offres  % du corpus
Cloud (Maroc)
GCP                     85         22.3
Azure                   80         21.0
AWS                     56         14.7
s3                       8          2.1
sagemaker                2          0.5
Azure Data Factory       2          0.5
Azure DevOps             2          0.5
AWS Glue                 1          0.3

>> Ops & MLOps <<
                     Offres  % du corpus
Ops & MLOps (Maroc)
Docker                   58         15.2
CI/CD                    58         15.2
Kubernetes               32          8.4
mlflow                   16          4.2
Terraform                14          3.7
gitlab ci                 9          2.4
ansible                   6          1.6
jenkins                   6          1.6

>> Langages <<
                  Offres  % du corpus
Langages (Maroc)
Python               201         52.8
R                     69         18.1
Java                  49         12.9
Scala                 32          8.4
JavaScript            10          2.6
Go                     7          1.8
TypeScript             2          0.5
ruby                   1          0.3

>> Domaines <<
                  Offres  % du corpus
Domaines (Maroc)
finance               34          8.9
NLP                   20          5.2
retail                20          5.2
forecasting           14          3.7
automotive            12          3.1
Computer Vision       11          2.9
cybersecurity         10          2.6
fintech                4          1.0

>> Autres <<
                Offres  % du corpus
Autres (Maroc)
Power BI           105         27.6
Statistics          81         21.3
Agile               63         16.5
Tableau             60         15.7
consulting          51         13.4
Excel               41         10.8
Big Data            38         10.0
Git                 35          9.2

## I.6 Écosystème frameworks d'IA générative au Maroc

In [7]:
section_frameworks_genai(df_maroc, 'Maroc')

                         Offres  % du corpus
Framework GenAI (Maroc)
LangChain                     4          1.0
LlamaIndex                    1          0.3

## I.7 Recherche vs Application/Production

In [8]:
section_recherche_vs_applied(df_maroc, 'Maroc')

                        Offres  % du corpus
Orientation (Maroc)
Recherche                   70         18.4
Application/Production     311         81.6

---

# Partie II : Marché Data & IA International (3 086 fiches)

## II.1 Vue d'ensemble du corpus international

In [9]:
section_vue_ensemble(df_international, 'International')

=== Vue d'ensemble (International) ===
Fiches totales : 3086
Sources distinctes : 1 (intl-ai-corpus)
Période couverte : 2025-08 -> 2026-04 (6 mois distincts)
Entreprises distinctes : 1378
Postes managériaux (lead, head, director, manager) : 459 (14.9 %)
Postes à interface client (sales, customer success, solutions eng.) : 692 (22.4 %)

## II.2 Distribution par type de poste

In [10]:
section_distribution_type(df_international, 'International')

                               Offres  % du corpus
Type de poste (International)
AI-First                         2257         73.1
AI-Support                        742         24.0
ML-First                           66          2.1
Inconnu                            21          0.7

## II.3 Top employeurs à l'international

In [11]:
section_top_entreprises(df_international, 'International', top=20)

                                   Offres
Top 20 employeurs (International)
Capital One                            56
Citi                                   39
Jack & Jill AI                         37
Optum                                  32
Thomson Reuters                        29
G2i                                    28
NVIDIA                                 24
Wolters Kluwer                         20
Wells Fargo                            20
Hewlett Packard Enterprise             19
BlackRock                              18
Celonis                                18
OpenAI                                 16
Visa Inc,                              16
Ecolab                                 15
Autodesk                               15
Scale AI                               14
Barclays                               14
S&P Global                             13
GEICO                                  12

## II.4 Top intitulés de poste à l'international

In [12]:
section_top_titres(df_international, 'International', top=10)

                                           Offres
Top 10 intitulés de poste (International)
AI Engineer                                   148
Senior AI Engineer                             98
Applied AI Engineer                            45
AI/ML Engineer                                 32
Lead AI Engineer                               29
Staff AI Engineer                              27
Senior AI/ML Engineer                          25
Principal AI Engineer                          22
Senior Applied AI Engineer                     16
AI Developer                                   15

## II.5 Compétences par famille (10 catégories)

In [13]:
section_competences_par_famille(df_international, 'International', top=10)

=== Top 10 compétences par famille (International) ===

>> IA générative <<
                               Offres  % du corpus
IA générative (International)
Prompt Engineering               1149         37.2
RAG                              1053         34.1
LangChain                         722         23.4
Agents                            697         22.6
LLM                               697         22.6
LangGraph                         390         12.6
OpenAI API                        286          9.3
LlamaIndex                        234          7.6
GenAI                             216          7.0
Embeddings                        199          6.4

>> Machine Learning <<
                                  Offres  % du corpus
Machine Learning (International)
PyTorch                              679         22.0
TensorFlow                           471         15.3
scikit-learn                         264          8.6
Fine-tuning                          242          7.8
HuggingFace                          174          5.6
Deep Learning                        161          5.2
Machine Learning                     154          5.0
Model Evaluation                     116          3.8
Reinforcement Learning               105          3.4
Embeddings                            98          3.2

>> Web & APIs <<
                            Offres  % du corpus
Web & APIs (International)
REST APIs                      762         24.7
React                          464         15.0
FastAPI                        347         11.2
Microservices                  208          6.7
APIs                           164          5.3
Node.js                        129          4.2
Next.js                        121          3.9
Flask                          116          3.8
GraphQL                         98          3.2
Angular                         98          3.2

>> Bases de données <<
                                  Offres  % du corpus
Bases de données (International)
Vector Databases                     545         17.7
PostgreSQL                           396         12.8
Pinecone                             216          7.0
Snowflake                            165          5.3
Weaviate                             151          4.9
SQL                                  147          4.8
Redis                                146          4.7
MongoDB                              127          4.1
BigQuery                              92          3.0
pgvector                              90          2.9

>> Data Engineering <<
                                  Offres  % du corpus
Data Engineering (International)
Data Pipelines                       272          8.8
Kafka                                205          6.6
Spark                                180          5.8
Airflow                              170          5.5
Databricks                           163          5.3
Pandas                               117          3.8
ETL                                   92          3.0
PySpark                               64          2.1
NumPy                                 59          1.9
dbt                                   54          1.7

>> Cloud <<
                       Offres  % du corpus
Cloud (International)
AWS                      1254         40.6
Azure                     863         28.0
GCP                       846         27.4
AWS Bedrock               155          5.0
AWS Lambda                104          3.4
Vertex AI                  96          3.1
SageMaker                  79          2.6
AWS SageMaker              71          2.3
AWS S3                     62          2.0
Azure OpenAI               58          1.9

>> Ops & MLOps <<
                             Offres  % du corpus
Ops & MLOps (International)
Docker                         1079         35.0
CI/CD                          1039         33.7
Kubernetes                      879         28.5
MLOps                           388         12.6
Terraform                       328         10.6
Git                             272          8.8
MLflow                          217          7.0
GitHub Actions                  157          5.1
Jenkins                         135          4.4
Observability                   125          4.1

>> Langages <<
                          Offres  % du corpus
Langages (International)
Python                      2573         83.4
TypeScript                   630         20.4
SQL                          574         18.6
Java                         562         18.2
Go                           366         11.9
JavaScript                   354         11.5
C++                          203          6.6
C#                           193          6.3
Node.js                      116          3.8
Scala                        115          3.7

>> Domaines <<
                          Offres  % du corpus
Domaines (International)
NLP                          308         10.0
Computer Vision              137          4.4
OCR                           14          0.5
Reinforcement Learning        11          0.4
Cybersecurity                 10          0.3
HIPAA                          9          0.3
HL7                            9          0.3
FHIR                           9          0.3
NLU                            6          0.2
speech recognition             6          0.2

>> Autres <<
                        Offres  % du corpus
Autres (International)
Distributed Systems        131          4.2
Agile                       53          1.7
Salesforce                  39          1.3
Cursor                      35          1.1
Jira                        30          1.0
n8n                         29          0.9
Agile/Scrum                 29          0.9
GitHub Copilot              25          0.8
Power BI                    25          0.8
GDPR                        23          0.7

## II.6 Écosystème frameworks d'IA générative à l'international

In [14]:
section_frameworks_genai(df_international, 'International')

                                 Offres  % du corpus
Framework GenAI (International)
LangChain                           722         23.4
LangGraph                           390         12.6
LlamaIndex                          234          7.6
CrewAI                              184          6.0
AutoGen                             129          4.2
Haystack                             24          0.8
Semantic Kernel                      73          2.4

## II.7 Recherche vs Application/Production

In [15]:
section_recherche_vs_applied(df_international, 'International')

                             Offres  % du corpus
Orientation (International)
Recherche                        94          3.0
Application/Production         2992         97.0

---

# Partie III : Comparaison Maroc vs International

Synthèse transverse. On cherche les **écarts marquants** entre les deux
marchés pour préparer la soutenance et nourrir le rapport méthodologique L5.

## III.1 Tableau comparatif des types de postes

In [16]:
cnt_ma = df_maroc['ai_type'].value_counts(normalize=True) * 100
cnt_intl = df_international['ai_type'].value_counts(normalize=True) * 100
tableau = pd.DataFrame({
    '% Maroc': cnt_ma.round(1),
    '% International': cnt_intl.round(1),
}).fillna(0.0)
tableau.index = [TYPES_FR.get(t, t) for t in tableau.index]
tableau.index.name = 'Type de poste'
tableau['Écart (INTL - MA)'] = (tableau['% International'] - tableau['% Maroc']).round(1)
tableau.sort_values('% International', ascending=False)

                % Maroc  % International  Écart (INTL - MA)
Type de poste
AI-First           12.1             73.1               61.0
AI-Support          0.0             24.0               24.0
ML-First           33.9              2.1              -31.8
Inconnu             0.0              0.7                0.7
Data Analytics     54.1              0.0              -54.1

## III.2 Top 20 compétences (Maroc vs International)

Agrégation sur les 10 familles. Tri par fréquence dans le corpus international (plus grand, donc plus stable statistiquement).

In [17]:
def comparaison_skills(df_a, df_b, top=30):
    skills_intl = top_skills_global(df_b, top=top).index.tolist()
    rows = []
    for skill in skills_intl:
        n_a = jobs_avec_skill(df_a, skill)
        n_b = jobs_avec_skill(df_b, skill)
        rows.append({
            'Compétence': skill,
            'Offres Maroc': n_a,
            '% Maroc': round(n_a / max(len(df_a), 1) * 100, 1),
            'Offres INTL': n_b,
            '% INTL': round(n_b / max(len(df_b), 1) * 100, 1),
        })
    t = pd.DataFrame(rows).set_index('Compétence')
    t['Écart (% INTL - % Maroc)'] = (t['% INTL'] - t['% Maroc']).round(1)
    return t


comparaison_skills(df_maroc, df_international, top=20)

,Offres Maroc,% Maroc,Offres INTL,% INTL,Écart (% INTL - % Maroc)
Compétence,,,,,
Python,201,52.8,2573,83.4,30.6
AWS,56,14.7,1436,46.5,31.8
Prompt Engineering,2,0.5,1159,37.6,37.1
Docker,58,15.2,1094,35.5,20.3
RAG,11,2.9,1343,43.5,40.6
CI/CD,58,15.2,1114,36.1,20.9
Kubernetes,32,8.4,909,29.5,21.1
Azure,80,21.0,1076,34.9,13.9
GCP,85,22.3,897,29.1,6.8
REST APIs,7,1.8,765,24.8,23.0
SQL,225,59.1,1089,35.3,-23.8
LangChain,4,1.0,731,23.7,22.7
LLM,24,6.3,1674,54.2,47.9
Agents,13,3.4,813,26.3,22.9
PyTorch,35,9.2,680,22.0,12.8
TypeScript,2,0.5,639,20.7,20.2
Java,54,14.2,823,26.7,12.5
Vector Databases,0,0.0,559,18.1,18.1
React,9,2.4,493,16.0,13.6
TensorFlow,36,9.4,478,15.5,6.1

## III.3 Écarts les plus marquants

Quelles compétences sont **massivement plus demandées** à l'international qu'au Maroc, et **lesquelles** sont surreprésentées au Maroc ?

In [18]:
tab = comparaison_skills(df_maroc, df_international, top=50)

print("=== Top 10 compétences SUR-représentées à l'international vs Maroc ===")
print(tab.sort_values('Écart (% INTL - % Maroc)', ascending=False).head(10).to_string())
print()
print('=== Top 10 compétences SUR-représentées au Maroc vs international ===')
print(tab.sort_values('Écart (% INTL - % Maroc)', ascending=True).head(10).to_string())

=== Top 10 compétences SUR-représentées à l'international vs Maroc ===
                    Offres Maroc  % Maroc  Offres INTL  % INTL  Écart (% INTL - % Maroc)
Compétence
LLM                           24      6.3         1674    54.2                      47.9
RAG                           11      2.9         1343    43.5                      40.6
Prompt Engineering             2      0.5         1159    37.6                      37.1
AWS                           56     14.7         1436    46.5                      31.8
Python                       201     52.8         2573    83.4                      30.6
REST APIs                      7      1.8          765    24.8                      23.0
Agents                        13      3.4          813    26.3                      22.9
LangChain                      4      1.0          731    23.7                      22.7
Go                            19      5.0          842    27.3                      22.3
Kubernetes                    32      8.4          909    29.5                      21.1

=== Top 10 compétences SUR-représentées au Maroc vs international ===
              Offres Maroc  % Maroc  Offres INTL  % INTL  Écart (% INTL - % Maroc)
Compétence
SQL                    225     59.1         1089    35.3                     -23.8
Spark                   73     19.2          231     7.5                     -11.7
Airflow                 38     10.0          181     5.9                      -4.1
Databricks              29      7.6          206     6.7                      -0.9
Kafka                   27      7.1          208     6.7                      -0.4
Snowflake               21      5.5          180     5.8                       0.3
scikit-learn            25      6.6          264     8.6                       2.0
MLflow                  16      4.2          236     7.6                       3.4
GenAI                   19      5.0          278     9.0                       4.0
CrewAI                   0      0.0          184     6.0                       6.0

---

## Synthèse exécutive (slide M9 à M12 de la soutenance)

Reprise des chiffres clés issus des Parties I à III, formatés en bullet
points pour la slide de conclusion.

In [19]:
print('=' * 70)
print("   SKILLNAV : Synthèse exécutive du corpus (mai 2026)")
print('=' * 70)

print(f'\n>> Volumétrie')
print(f'   - Corpus Maroc        : {len(df_maroc):>5} offres   /  6 sources')
print(f'   - Corpus International: {len(df_international):>5} offres   /  builtin.com (6 pays)')
print(f'   - Total               : {len(df_maroc)+len(df_international):>5} offres')

print(f'\n>> Profil dominant')
ma_top = df_maroc['ai_type'].value_counts().idxmax()
intl_top = df_international['ai_type'].value_counts().idxmax()
ma_pct = df_maroc['ai_type'].value_counts(normalize=True).max() * 100
intl_pct = df_international['ai_type'].value_counts(normalize=True).max() * 100
print(f'   - Maroc        : {TYPES_FR[ma_top]:<15} ({ma_pct:.0f} %)  -> marché encore très Data Analyst')
print(f'   - International: {TYPES_FR[intl_top]:<15} ({intl_pct:.0f} %)  -> marché pleinement basculé GenAI')

print(f'\n>> Top 3 compétences les plus sur-représentées à l\'international')
ecarts = tab.sort_values('Écart (% INTL - % Maroc)', ascending=False).head(3)
for skill, row in ecarts.iterrows():
    print(f'   - {skill:<22}: {row["% Maroc"]:>5.1f}% MA   vs  {row["% INTL"]:>5.1f}% INTL   (+{row["Écart (% INTL - % Maroc)"]} pts)')

print(f'\n>> Lecture pour la soutenance')
print("   1. Le marché marocain reste majoritairement Data Analyst (SQL, Excel, Power BI).")
print("   2. La GenAI (RAG, LangChain, prompt engineering) n'a pas encore percé au Maroc.")
print("   3. Les écarts de stack (Docker, K8s, MLOps) signalent un retard MLOps marocain.")
print("   4. L'axe gap analysis curriculum ENSA vs marché est donc PERTINENT.")
print("   5. Visualisations soutenance : voir 01_visualisations.ipynb (16 figures PNG).")
print('=' * 70)

======================================================================
   SKILLNAV : Synthèse exécutive du corpus (mai 2026)
======================================================================

>> Volumétrie
   - Corpus Maroc        :   381 offres   /  6 sources
   - Corpus International:  3086 offres   /  builtin.com (6 pays)
   - Total               :  3467 offres

>> Profil dominant
   - Maroc        : Data Analytics  (54 %)  -> marché encore très Data Analyst
   - International: AI-First        (73 %)  -> marché pleinement basculé GenAI

>> Top 3 compétences les plus sur-représentées à l'international
   - LLM                   :   6.3% MA   vs   54.2% INTL   (+47.9 pts)
   - RAG                   :   2.9% MA   vs   43.5% INTL   (+40.6 pts)
   - Prompt Engineering    :   0.5% MA   vs   37.6% INTL   (+37.1 pts)

>> Lecture pour la soutenance
   1. Le marché marocain reste majoritairement Data Analyst (SQL, Excel, Power BI).
   2. La GenAI (RAG, LangChain, prompt engineering) n'a pas encore percé au Maroc.
   3. Les écarts de stack (Docker, K8s, MLOps) signalent un retard MLOps marocain.
   4. L'axe gap analysis curriculum ENSA vs marché est donc PERTINENT.
   5. Visualisations soutenance : voir 01_visualisations.ipynb (16 figures PNG).
======================================================================